FiMA/Web/Fima.Web/Areas/FrontOffice/Controllers/ClientController.cs
namespace Fima.Web.Areas.FrontOffice.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;
    using Common;
    using Data.DbModels;
    using Infrastructure.Mapping;
    using Microsoft.AspNet.Identity;
    using Models.Client;
    using Services.Data.Contracts;
    using Web.Controllers;

    public class ClientController : BaseController
    {
        private readonly ICountriesService countries;
        private readonly ICitiesService cities;
        private readonly IClientsService clients;
        private readonly IMunicipalitiesService municipalities;
        private readonly IBanksService banks;

        public ClientController(
            ICountriesService countries,
            ICitiesService cities,
            IClientsService clients,
            IMunicipalitiesService municipalities,
            IBanksService banks)
        {
            this.countries = countries;
            this.cities = cities;
            this.clients = clients;
            this.municipalities = municipalities;
            this.banks = banks;
        }

        // GET: FrontOffice/Client/AllClientIds
        // for ajax request - returns all personal Ids to check if input exists
        [HttpGet]
        public JsonResult AllClientIds()
        {
            var clientsPersonalIds = this.clients.AllPersonalIds();

            return this.Json(clientsPersonalIds, JsonRequestBehavior.AllowGet);
        }

        // GET: FrontOffice/Client/Representatives
        // for ajax request search and fill representative select form
        [HttpGet]
        public JsonResult Representatives()
        {
            var representatives = this.clients.GetAll()
                .To<RepSelectViewModel>()
                .ToList();

            return this.Json(representatives, JsonRequestBehavior.AllowGet);
        }

        // GET: FrontOffice/Client/Register
        [HttpGet]
        public ActionResult Register()
        {
            var model = new ClientRegisterViewModel();

            model.Countries = this.countries.AllNames();
            model.Cities = this.cities.AllNames();
            model.Banks = this.banks.AllNames();
            model.Municipalities = this.municipalities.AllNames();
            model.PERSONAL_ID_DATE = DateTime.Today.ToString("dd/MM/yyyy");
            model.CLIENT_BIRTHDATE = DateTime.Today.ToString("dd/MM/yyyy");

            return this.View(model);
        }

        // POST: FrontOffice/Client/Register
        [HttpPost]
        public ActionResult Register(ClientRegisterViewModel model)
        {
            var id = this.User.Identity.GetUserId();

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            // проверка за физическо или юридическо лице и създаване на FULL_NAME
            if (model.TYPE_PERSON == GlobalConstants.PerTypes[0] ||
                model.TYPE_PERSON == GlobalConstants.PerTypes[2])
            {
                model.FULL_NAME = model.FirmName;
            }
            else
            {
                model.FULL_NAME = $"{model.FIRSTNAME} {model.SECONDNAME} {model.LASTNAME}";
            }

            // TODO: създаване на тези неща
            model.CREATED_BY = int.Parse(id);
            model.CREATED_WHEN = DateTime.Now.ToString();

            var clientNewId = this.clients.GetNewId();
            model.CLIENTID = clientNewId;

            var tempStr = "000000";
            var i2 = tempStr.Length - clientNewId.ToString().Length;
            var tempstr2 = tempStr.Substring(0, i2);
            var clstring = "AC";
            model.CLIENTID_STRING = clstring + tempstr2.ToString() + clientNewId.ToString();

            /*Dim rst As ADODB.Recordset
    myuser = conn_sql.myuser   '' DLookup("[user]", "current_user")
    'mypass = DLookup("[pass]", "current_user")
    Dim userid As Integer
    userid = conn_sql.userid   ''DLookup("[user_int]", "current_user")
    'Call CONNECT_SQL
    'conn.Open MYCONN
    ''''''''''''''''''''''''''''''''''''''''''''''''''''
    Dim udid As String
    udid = conn_sql.udid '' Trim(DLookup("[udid]", "tblcurrentud"))
    ''''''''''''''''''''''''''''''''''''''''''''''''''''


    '////////////////////////////////////////////////////////////////
    Dim i As Double
    rst = conn.Execute("exec sp_getmaxinvid")
    If rst.EOF Then
        i = 1
    Else
        i = rst.Fields("max_id").Value
        i = i + 1
    End If

    '////////////////////////////////////////////////////////////////
    'GET USER CLIENT STRING
    Dim clstring As String
    rst = conn.Execute("exec sp_getuserstring " _
        & userid & "")
    If rst.EOF Then
        MsgBox("Не мога да намеря код за потребителя!")
        Exit Sub
    Else
        clstring = rst.Fields("strindex").Value
    End If
    '///////////////////////////////////////////////////////////////
    Dim tempstr As String
    Dim tempstr2 As String
    Dim i2 As Integer
    Dim clidstring As String


    If udid = "AC" Then
        tempstr = "000000"
        i2 = Len(tempstr) - Len(Trim(i))
        tempstr2 = msvb.Left(tempstr, i2)
        clidstring = clstring & "-" & tempstr2 & i
    Else
        tempstr = "000000"
        i2 = Len(tempstr) - Len(Trim(i))
        tempstr2 = msvb.Left(tempstr, i2)
        clidstring = clstring & tempstr2 & i
    End If


    '///////////////////////////////////////////////////////////////////
    Dim fullnm As String
    If Me.cmbPERTYPE.Text = "БЪЛГАРСКО ФИЗИЧЕСКО ЛИЦЕ" Or Me.cmbPERTYPE.Text = "ЧУЖДО ФИЗИЧЕСКО ЛИЦЕ" Then
        fullnm = Me.txtFNAME.Text & " " & Me.txtSNAME.Text & " " & Me.txtLNAME.Text
    Else
        fullnm = Me.txtNAME.Text
    End If
    '///////////////////////////////////////////////////////////////////
    Dim crwhen As Date
    crwhen = Now()
    '///////////////////////////////////////////////////////////////////

    Dim dcit As String
    If Me.checkRES.Checked = True Then
        dcit = "YES"
    Else
        dcit = "NO"
    End If*/
            var newClient = new INVESTORS_FUNDS();
            this.Mapper.Map(model, newClient);
            this.clients.CreateClient(newClient);
            return this.RedirectToAction("Index", "Home");
        }
    }
}

FiMA/Web/Fima.Web/Areas/BackOffice/Views/Shared/_BackOfficeMenu.cshtml
<ul>
    <li class="menu-item toggle">
        <i class="fa fa-chevron-down"></i>фронт офис
        <ul class="submenu">
            <li class="submenu-item"><a class="links" href="#">регистриране на клиент</a></li>
            <li class="submenu-item"><a class="links" href="#">преглед на клиенти</a></li>
            <li class="submenu-item"><a class="links" href="#">регистриране на договор</a></li>
            <li class="submenu-item"><a class="links" href="#">преглед на договорите</a></li>
            <li class="submenu-item"><a class="links" href="#">нова поръчка клиент</a></li>
            <li class="submenu-item"><a class="links" href="#">преглед на поръчките</a></li>
            <li class="submenu-item"><a class="links" href="#">преглед сделки клиенти</a></li>
            <li class="submenu-item"><a class="links" href="#">справка порфейл за фонд</a></li>
            <li class="submenu-item"><a class="links" href="#">справка порфейл всички фондове</a></li>
            <li class="submenu-item"><a class="links" href="#">справка НСА фондове</a></li>
            <li class="submenu-item"><a class="links" href="#">справка остатъци</a></li>
            <li class="submenu-item"><a class="links" href="#">касови операции</a></li>
        </ul>
    </li>
    <li class="menu-item toggle">
        <i class="fa fa-chevron-down"></i>фронт офис schroders
        <ul class="submenu">
            <li class="submenu-item"><a class="links" href="#">регистриране на фонд</a></li>
            <li class="submenu-item"><a class="links" href="#">преглед на фондове</a></li>
            <li class="submenu-item"><a class="links" href="#">регистриране на договор</a></li>
            <li class="submenu-item"><a class="links" href="#">преглед договори schroders</a></li>
            <li class="submenu-item"><a class="links" href="#">регистриране на поръчка</a></li>
            <li class="submenu-item"><a class="links" href="#">преглед на поръчки</a></li>
            <li class="submenu-item"><a class="links" href="#">регистриране на сделка</a></li>
            <li class="submenu-item"><a class="links" href="#">регистриране на к. събитие</a></li>
            <li class="submenu-item"><a class="links" href="#">преглед на сделки</a></li>
            <li class="submenu-item"><a class="links" href="#">факс за деня</a></li>
            <li class="submenu-item"><a class="links" href="#">справка портфейл</a></li>
            <li class="submenu-item"><a class="links" href="#">импорт на цени</a></li>
        </ul>
    </li>
    <li class="menu-item">
        <a class="links" href="@Url.Action("Index", "Client")"><i class="fa fa-chevron-right"></i>обработка на поръчки</a>
    </li>
    <li class="menu-item">
        <a class="links" href="@Url.Action("List", "Client")"><i class="fa fa-chevron-right"></i>рег. поръчка schroders</a>
    </li>
    <li class="menu-item">
        <a class="links" href="@Url.Action("Index", "Contract")"><i class="fa fa-chevron-right"></i>рег. сделка schroders</a>
    </li>
    <li class="menu-item toggle">
        <i class="fa fa-chevron-down"></i>емисии
        <ul class="submenu">
            <li class="submenu-item"><a class="links" href="#">нова емисия</a></li>
            <li class="submenu-item"><a class="links" href="#">преглед на емисии</a></li>
            <li class="submenu-item"><a class="links" href="#">добавяне валута</a></li>
            <li class="submenu-item"><a class="links" href="#">добавяне отрасъл</a></li>
            <li class="submenu-item"><a class="links" href="#">добавяне страна</a></li>
        </ul>
    </li>
    <li class="menu-item toggle">
        <i class="fa fa-chevron-down"></i>поръчки за портфейл
        <ul class="submenu">
            <li class="submenu-item"><a class="links" href="#">нова поръчка портфейл</a></li>
            <li class="submenu-item"><a class="links" href="#">преглед поръчки портфейл</a></li>
        </ul>
    </li>
    <li class="menu-item toggle">
        <i class="fa fa-chevron-down"></i>сделки за портфейл
        <ul class="submenu">
            <li class="submenu-item"><a class="links" href="#">нова сделка портфейл</a></li>
            <li class="submenu-item"><a class="links" href="#">преглед на сделки портфейл</a></li>
            <li class="submenu-item"><a class="links" href="#">корпоративно събитие</a></li>
        </ul>
    </li>
    <li class="menu-item toggle">
        <i class="fa fa-chevron-down"></i>дневници
        <ul class="submenu">
            <li class="submenu-item"><a class="links" href="#">поръчки клиенти</a></li>
            <li class="submenu-item"><a class="links" href="#">сделки клиенти</a></li>
            <li class="submenu-item"><a class="links" href="#">поръчки за портфейла</a></li>
            <li class="submenu-item"><a class="links" href="#">сделки за портфейл</a></li>
            <li class="submenu-item"><a class="links" href="#">ведомост получени съми на каса</a></li>
        </ul>
    </li>
</ul>

FiMA/Web/Fima.Web/Areas/BackOffice/Views/Shared/_Layout.cshtml
@using Fima.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FiMA</title>
    @Scripts.Render("~/bundles/jquery")
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">
    @Styles.Render("~/Content/css")
</head>
<body>
    <header>
        <nav>
            <div class="logo">
                @Html.ActionLink("FiMA", "Index", "Home", new { area = string.Empty }, new { @class = "page-brand" })
            </div>

            <div class="nav-bar">
                @Html.Partial("_LoginPartial")
            </div>
        </nav>
    </header>
    <main class="page-container">
        <div class="sidebar">
            <div class="burger">
                <div class="bar1"></div>
                <div class="bar2"></div>
                <div class="bar3"></div>
            </div>
            <div class="menu-item">
                <a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i>начало</a>
            </div>
            @if (this.User.IsInRole(GlobalConstants.BackOfficeRoleName) || this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
                Html.RenderPartial("_BackOfficeMenu");
            }
        </div>
        <div class="content">
            @RenderBody()
        </div>
    </main>
    <footer>
        <p class="footer-content">&copy; @DateTime.UtcNow.Year - <b>FiМА</b> <a href="">Всички права са запазени.</a> </p>
    </footer>

    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/local")
</body>
</html>